const config = {
	xLabel: {
		width: 20,
	},
	barValue: {
		width: 20,
	},
	barData: [
		{
			id: 1,
			stateName: 'Andhra Pradesh',
			capital: 'Hyderabad (de jure)\nAmaravati '
			+ '(de facto)\nVisakhapatnam(Administrative )',
			area: '1,60,205 Sq Km',
			population: 49670000,
			stateEstablished: '01-10-1953',
			largestCity: 'Visakhapatnam',
			languages: 'Telugu ',
		},
		{
			id: 2,
			stateName: 'Arunachal Pradesh',
			capital: 'Itanagar',
			area: '83,743 sq. km',
			population: 1382611,
			stateEstablished: '20-02-1987',
			largestCity: 'Itanagar',
			languages: 'Monpa, Miji, Aka, Sherdukpen, \nNyishi,'
			+ ' Apatani, Tagin, Hill \nMiri, Adi, Digaru-Mismi, '
			+ 'Idu-Mishmi,\n Khamti, Miju-Mishmi, Nocte, Tangsa \nand Wancho.',
		},
		{
			id: 3,
			stateName: 'Assam',
			capital: 'Dispur',
			area: '78,438 sq. km',
			population: 31169272,
			stateEstablished: '26-01-1950',
			largestCity: 'Guwahati',
			languages: 'Assamese',
		},
		{
			id: 4,
			stateName: 'Bihar ',
			capital: 'Patna',
			area: '94,163 sq. km',
			population: 103804637,
			stateEstablished: '26-01-1950',
			largestCity: 'Patna',
			languages: 'Hindi ,Urdu',
		},
		{
			id: 5,
			stateName: 'Chhattisgarh',
			capital: 'Naya Raipur',
			area: '1,36,034 sq. km',
			population: 25540196,
			stateEstablished: '01-11-2000',
			largestCity: 'Raipur',
			languages: 'Hindi',
		},
		{
			id: 6,
			stateName: 'Goa',
			capital: 'Panaji',
			area: '3,702 sq. km',
			population: 1457723,
			stateEstablished: '30-05-1987',
			largestCity: 'Vasco da Gama',
			languages: 'Konkani(official Language),\nMarathi,'
			+ ' Hindi, English, Kannada',
		},
		{
			id: 7,
			stateName: 'Gujarat',
			capital: 'Gandhinagar',
			area: '1,96,024 sq. km',
			population: 60383628,
			stateEstablished: '01-05-1960',
			largestCity: 'Ahmedabad',
			languages: 'Gujarati',
		},
		{
			id: 8,
			stateName: 'Haryana',
			capital: 'Chandigarh',
			area: '44,212 sq. km',
			population: 25353081,
			stateEstablished: '01-11-1966',
			largestCity: 'Faridabad',
			languages: 'Hindi',
		},
		{
			id: 9,
			stateName: 'Himachal Pradesh',
			capital: 'Shimla (Summer)\nDharamsala (Winter)',
			area: '55,673 sq. km',
			population: 6856509,
			stateEstablished: '25-01-1971',
			largestCity: 'Shimla ',
			languages: 'Hindi & Pahari',
		},
		{
			id: 10,
			stateName: 'Jharkhand',
			capital: 'Ranchi',
			area: '79,714 sq. km',
			population: 31169272,
			stateEstablished: '15-11-2000',
			largestCity: 'Jamshedpur',
			languages: 'Hindi',
		},
		{
			id: 11,
			stateName: 'Karnataka',
			capital: 'Bangalore',
			area: '1,91,791 sq. km',
			population: 61130704,
			stateEstablished: '01-11-1956',
			largestCity: 'Bengaluru',
			languages: 'Kannada',
		},
		{
			id: 12,
			stateName: 'Kerala',
			capital: 'Thiruvananthapuram',
			area: '38,863 sq. km',
			population: 33387677,
			stateEstablished: '01-11-1956',
			largestCity: 'Malappuram',
			languages: 'Malayalam',
		},
		{
			id: 13,
			stateName: 'Madhya Pradesh',
			capital: 'Bhopal',
			area: '3,08,000 sq. km',
			population: 72597565,
			stateEstablished: '01-11-1956',
			largestCity: 'Indore',
			languages: 'Hindi',
		},
		{
			id: 14,
			stateName: 'Maharashtra',
			capital: 'Mumbai ',
			area: '3,07,713 sq. km',
			population: 112372972,
			stateEstablished: '01-05-1960',
			largestCity: 'Mumbai ',
			languages: 'Marathi',
		},
		{
			id: 15,
			stateName: 'Manipur',
			capital: 'Imphal',
			area: '22,327 sq. km',
			population: 2721756,
			stateEstablished: '21-01-1972',
			largestCity: 'manipur ',
			languages: 'Manipuri',
		},
		{
			id: 16,
			stateName: 'Meghalaya',
			capital: 'Shillong',
			area: '22,429 sq. km',
			population: 2964007,
			stateEstablished: '21-01-1972',
			largestCity: 'Shillong',
			languages: 'Khasi, Garo and English',
		},
		{
			id: 17,
			stateName: 'Mizoram',
			capital: 'Aizawl',
			area: '21,081 sq. km',
			population: 1091014,
			stateEstablished: '20-02-1987',
			largestCity: 'Aizawl',
			languages: 'Mizo and English',
		},
		{
			id: 18,
			stateName: 'Nagaland',
			capital: 'Kohima',
			area: '16,579 sq. km',
			population: 1980602,
			stateEstablished: '01-12-1963',
			largestCity: 'Dimapur',
			languages: 'English, Hindi and 16 tribal dialects',
		},
		{
			id: 19,
			stateName: 'Odisha',
			capital: 'Bhubaneshwar',
			area: '1,55,707 sq. km',
			population: 41947358,
			stateEstablished: '26-01-1950',
			largestCity: 'Bhubaneswar',
			languages: 'Oriya',
		},
		{
			id: 20,
			stateName: 'Punjab',
			capital: 'Chandigarh',
			area: '50,362 sq. km',
			population: 27704236,
			stateEstablished: '01-11-1966',
			largestCity: 'Ludhiana',
			languages: 'Punjabi',
		},
		{
			id: 21,
			stateName: 'Rajasthan',
			capital: 'Jaipur',
			area: '3,42,239 sq. km',
			population: 68621012,
			stateEstablished: '01-11-1956',
			largestCity: 'Jaipur ',
			languages: 'Hindi and Rajasthani',
		},
		{
			id: 22,
			stateName: 'Sikkim',
			capital: 'Gangtok',
			area: '7,096 sq. km',
			population: 607688,
			stateEstablished: '16-05-1975',
			largestCity: 'Gangtok',
			languages: 'Lepcha, Bhutia and Nepali',
		},
		{
			id: 23,
			stateName: 'Tamil Nadu',
			capital: 'Chennai',
			area: '1,30,058 sq. km',
			population: 72138958,
			stateEstablished: '26-01-1950',
			largestCity: 'Tamil',
			languages: 'Chennai',
		},
		{
			id: 24,
			stateName: 'Telangana ',
			capital: 'Hyderabad',
			area: '112,077 Sq. Kms',
			population: 3500400,
			stateEstablished: '02-06-2014',
			largestCity: 'Hyderabad',
			languages: 'Telugu, Urdu',
		},
		{
			id: 25,
			stateName: 'Tripura',
			capital: 'Agartala',
			area: '10,491.69 km2',
			population: 3671032,
			stateEstablished: '21-01-1972',
			largestCity: 'Agartala',
			languages: 'Bengali and Kokborok',
		},
		{
			id: 26,
			stateName: 'Uttarakhand',
			capital: 'Gairsain (Summer)\nDehradun (Winter)',
			area: '53,484 sq. km',
			population: 10116752,
			stateEstablished: '26-01-1950',
			largestCity: 'Dehradun',
			languages: 'Hindi, Garhwali, Kumaoni',
		},
		{
			id: 27,
			stateName: 'Uttar Pradesh ',
			capital: 'Lucknow',
			area: '2,40,928 sq. km',
			population: 199581477,
			stateEstablished: '09-11-2000',
			largestCity: 'Lucknow',
			languages: 'Hindi and Urdu',
		},
		{
			id: 28,
			stateName: 'West Bengal',
			capital: 'Kolkata',
			area: '88,752 sq. km',
			population: 91347736,
			stateEstablished: '26-01-1950',
			largestCity: 'Kolkata',
			languages: 'Bengali',
		},
	],
};

export default config;
